### ISSUE TITLE
Kafka单机已连接，ZK连接失败，相关信息无法刷新

### ISSUE THREAD

**Issue by akinlong** [didi/KnowStreaming#1132]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>  3.3.0 </font>
* Operating System version :  <font size=4 color =red> rhel7.4 </font>
* Java version : <font size=4 color =red> 使用docker-compose latest镜像 </font>

### 重现该问题的步骤

1. docker-compose启动集群
   

2. 在页面配置单机kafka，配置如下
![image](https://github.com/didi/KnowStreaming/assets/11705474/1978176a-c4cb-40c6-a261-6731a3471145)

   

3. 显示集群状态异常，同时后端出现报错
![image](https://github.com/didi/KnowStreaming/assets/11705474/f201668f-dba6-4e3f-9f65-337e025c4efe)
![image](https://github.com/didi/KnowStreaming/assets/11705474/be66a896-07be-431d-a8f5-f8c6e5759c88)

### 预期结果

正常连接ZK并展示kafka信息

### 实际结果

无法连接ZK

---

如果有异常，请附上异常Trace:

```
2023-08-24 12:30:03.637 ERROR 11 --- [-2-10-thread-82] k.s.k.c.s.h.c.AbstractHealthCheckService : method=checkAndGetResult||clusterParam=ZookeeperParam(zkAddressList=[Tuple{v1=192.168.162.12, v2=2181}], zkConfig=null)||clusterHealthConfig=HealthAmountRatioConfig(amount=100000, ratio=0.8)||errMsg=exception!

java.lang.NullPointerException: null
        at com.xiaojukeji.know.streaming.km.core.service.health.checker.zookeeper.HealthCheckZookeeperService.checkWatchCount(HealthCheckZookeeperService.java:188)
        at com.xiaojukeji.know.streaming.km.core.service.health.checker.AbstractHealthCheckService.checkAndGetResult(AbstractHealthCheckService.java:50)
        at com.xiaojukeji.know.streaming.km.task.kafka.health.AbstractHealthCheckTask.checkAndGetResult(AbstractHealthCheckTask.java:109)
        at com.xiaojukeji.know.streaming.km.task.kafka.health.AbstractHealthCheckTask.lambda$calAndUpdateHealthCheckResult$0(AbstractHealthCheckTask.java:60)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2023-08-24 12:30:03.637  INFO 11 --- [-2-10-thread-82] .x.k.s.k.c.s.v.BaseVersionControlService : method=doVCHandler||clusterId=2||action=ApproximateDataSize||type=ZookeeperMetric||param={"clusterPhyId":2,"metricName":"ApproximateDataSize","zkAddressList":[{"v1":"192.168.162.12","v2":2181}]}
2023-08-24 12:30:03.638 ERROR 11 --- [-2-10-thread-82] k.s.k.c.s.h.c.AbstractHealthCheckService : method=checkAndGetResult||clusterParam=ZookeeperParam(zkAddressList=[Tuple{v1=192.168.162.12, v2=2181}], zkConfig=null)||clusterHealthConfig=HealthAmountRatioConfig(amount=524288000, ratio=0.8)||errMsg=exception!

java.lang.NullPointerException: null
        at com.xiaojukeji.know.streaming.km.core.service.health.checker.zookeeper.HealthCheckZookeeperService.checkApproximateDataSize(HealthCheckZookeeperService.java:260)
        at com.xiaojukeji.know.streaming.km.core.service.health.checker.AbstractHealthCheckService.checkAndGetResult(AbstractHealthCheckService.java:50)
        at com.xiaojukeji.know.streaming.km.task.kafka.health.AbstractHealthCheckTask.checkAndGetResult(AbstractHealthCheckTask.java:109)
        at com.xiaojukeji.know.streaming.km.task.kafka.health.AbstractHealthCheckTask.lambda$calAndUpdateHealthCheckResult$0(AbstractHealthCheckTask.java:60)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2023-08-24 12:30:03.639  INFO 11 --- [-2-10-thread-82] .x.k.s.k.c.s.v.BaseVersionControlService : method=doVCHandler||clusterId=2||action=NumAliveConnections||type=ZookeeperMetric||param={"clusterPhyId":2,"metricName":"NumAliveConnections","zkAddressList":[{"v1":"192.168.162.12","v2":2181}]}
2023-08-24 12:30:09.672  INFO 11 --- [kTP-6-thread-14] kafka.zookeeper.ZooKeeperClient          : [ZooKeeperClient KS-ZK-ClusterPhyId-1] Closed.
2023-08-24 12:30:09.672 ERROR 11 --- [kTP-6-thread-14] c.x.k.s.k.p.kafka.KafkaAdminZKClient     : method=createZKClient||clusterPhyId=1||clusterPhy=ClusterPhy(id=1, createTime=Thu Aug 24 10:18:49 GMT+08:00 2023, updateTime=Thu Aug 24 11:28:26 GMT+08:00 2023, name=192.168.162.12, bootstrapServers=192.168.162.12:9092, kafkaVersion=2.8.1, zookeeper=192.168.162.12:2181, clientProperties={}, jmxProperties={"jmxPort":9999,"maxConn":10,"openSSL":false}, zkProperties=, authType=0, runState=1, description=)||msg=create ZK Client failed||errMsg=exception

java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2067)
        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:273)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:125)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1948)
        at kafka.zk.KafkaZkClient.apply(KafkaZkClient.scala)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.KafkaAdminZKClient.createZKClient(KafkaAdminZKClient.java:137)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.KafkaAdminZKClient.createZKClient(KafkaAdminZKClient.java:121)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.KafkaAdminZKClient.getClient(KafkaAdminZKClient.java:45)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl.getKafkaController(KafkaZKDAOImpl.java:153)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl$$FastClassBySpringCGLIB$$6e05ff5c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl$$EnhancerBySpringCGLIB$$64aa1c82.getKafkaController(<generated>)
        at com.xiaojukeji.know.streaming.km.core.service.kafkacontroller.impl.KafkaControllerServiceImpl.getControllerFromZKClient(KafkaControllerServiceImpl.java:186)
        at com.xiaojukeji.know.streaming.km.core.service.kafkacontroller.impl.KafkaControllerServiceImpl.getControllerFromKafka(KafkaControllerServiceImpl.java:45)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.SyncControllerTask.processClusterTask(SyncControllerTask.java:36)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.AbstractAsyncMetadataDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetadataDispatchTask.java:33)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2023-08-24 12:30:09.672 ERROR 11 --- [kTP-6-thread-14] k.s.k.c.s.k.i.KafkaControllerServiceImpl : method=getControllerFromZKClient||clusterPhyId=1||errMsg=exception

com.xiaojukeji.know.streaming.km.common.exception.NotExistException: kafka kafka-zk-client not exist due to create failed
        at com.xiaojukeji.know.streaming.km.persistence.kafka.KafkaAdminZKClient.getClient(KafkaAdminZKClient.java:47)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl.getKafkaController(KafkaZKDAOImpl.java:153)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl$$FastClassBySpringCGLIB$$6e05ff5c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl$$EnhancerBySpringCGLIB$$64aa1c82.getKafkaController(<generated>)
        at com.xiaojukeji.know.streaming.km.core.service.kafkacontroller.impl.KafkaControllerServiceImpl.getControllerFromZKClient(KafkaControllerServiceImpl.java:186)
        at com.xiaojukeji.know.streaming.km.core.service.kafkacontroller.impl.KafkaControllerServiceImpl.getControllerFromKafka(KafkaControllerServiceImpl.java:45)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.SyncControllerTask.processClusterTask(SyncControllerTask.java:36)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.AbstractAsyncMetadataDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetadataDispatchTask.java:33)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2023-08-24 12:30:09.672 ERROR 11 --- [kTP-6-thread-14] .t.k.m.AbstractAsyncMetadataDispatchTask : method=asyncProcessSubTask||taskName=SyncControllerTask||clusterPhyId=1||taskResult=TaskResult(code=-1, message=kafka kafka-zk-client not exist due to create failed)||msg=failed
```

**Comment by akinlong** [comment]
![image](https://github.com/didi/KnowStreaming/assets/11705474/5067f109-5867-4711-bbc3-c07cbd8ebeff)
使用offset explorer可以正常连接。
Kafka集群版本2.8.1

**Comment by ZQKC** [comment]
> ![image](https://user-images.githubusercontent.com/11705474/262861047-5067f109-5867-4711-bbc3-c07cbd8ebeff.png) 使用offset explorer可以正常连接。 Kafka集群版本2.8.1

ks所在机器，用zk客户端连接一下zk看看是否可以成功。

**Comment by akinlong** [comment]
> 

![image](https://github.com/didi/KnowStreaming/assets/11705474/54b127f2-f3be-4354-902a-4de61b6ba97b)
容器所在服务器可以正常连接对端zk

**Comment by akinlong** [comment]
> > ![image](https://user-images.githubusercontent.com/11705474/262861047-5067f109-5867-4711-bbc3-c07cbd8ebeff.png) 使用offset explorer可以正常连接。 Kafka集群版本2.8.1
> 
> ks所在机器，用zk客户端连接一下zk看看是否可以成功。

![image](https://github.com/didi/KnowStreaming/assets/11705474/2f9c2e05-baa0-44c8-84df-dee59156adf3)
同时，将zk客户端cp进ks manager容器后，执行连接也是成功的

**Comment by akinlong** [comment]
![image](https://github.com/didi/KnowStreaming/assets/11705474/d8873863-f04b-45cf-af42-c13e323d3bb1)
从ZK服务端日志来看，是客户端主动关闭了连接。
同时zk的四字已开启。

**Comment by akinlong** [comment]
神奇的事情发生了，手动在zk的数据表配置中把两个超时时间配置延长以后，就可以正常连接了，但是从抓包情况来看，连接时间貌似没有超过设置

**Comment by niejian** [comment]
> 神奇的事情发生了，手动在zk的数据表配置中把两个超时时间配置延长以后，就可以正常连接了，但是从抓包情况来看，连接时间貌似没有超过设置

哪个表来着？

**Comment by ZQKC** [comment]
> > 神奇的事情发生了，手动在zk的数据表配置中把两个超时时间配置延长以后，就可以正常连接了，但是从抓包情况来看，连接时间貌似没有超过设置
> 
> 哪个表来着？

我理解是 ks_km_physical_cluster 表

**Comment by xuexh0816** [comment]
> 神奇的事情发生了，手动在zk的数据表配置中把两个超时时间配置延长以后，就可以正常连接了，但是从抓包情况来看，连接时间貌似没有超过设置

请问 是在哪里增加配置呢 key是哪个

**Comment by jiangminbing** [comment]
![1701176461308](https://github.com/didi/KnowStreaming/assets/33618883/70adfa9d-8e83-45ec-afe7-e973abfea6f6)
我也遇到同样的问题，请问如何解决的？

**Comment by ZQKC** [comment]
> > 神奇的事情发生了，手动在zk的数据表配置中把两个超时时间配置延长以后，就可以正常连接了，但是从抓包情况来看，连接时间貌似没有超过设置
> 
> 请问 是在哪里增加配置呢 key是哪个

可以看doc下的文档，上面有关于ZK的配置

**Comment by ZQKC** [comment]
> ![1701176461308](https://private-user-images.githubusercontent.com/33618883/286257839-70adfa9d-8e83-45ec-afe7-e973abfea6f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1ODYyMjAsIm5iZiI6MTcwMTU4NTkyMCwicGF0aCI6Ii8zMzYxODg4My8yODYyNTc4MzktNzBhZGZhOWQtOGU4My00NWVjLWFmZTctZTk3M2FiZmVhNmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDA2NDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYmJlN2MwNTI3ZTczMjZkOGJmZTU0ODZjMjA4ODYwZmRjYmE3ZTNiMGYyZDE1NmZjZTIxN2YyMGRlYmI5NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IacEYu3Xxri0eNJJ_czHLsO9pogrHLF8KX2ZnE4TrcA) 我也遇到同样的问题，请问如何解决的？

这应该是获取ZK的指标失败导致的，可以执行一下四字命令试一下看看。

**Comment by jiangminbing** [comment]
解决这个问题需要在
zookeeper需要添加白名单配置，否则会被拒绝，到zookeepr 目录下
执行指令 ./zookeeper-shell.sh 127.0.0.1:2181
setAcl / ip:192.138.3.104:cdrwa,ip:127.0.0.1:cdrwa （注意要添加本机器IP）
执行完查看指令：getAcl /

**Comment by jiangminbing** [comment]
zookeeper config 中添加 不限制四字命令
修改zookeeper.properties 4lw.commands.whitelist=*
