### ISSUE TITLE
knowstraming支持接入带kerberos认证的kafak集群吗？

### ISSUE THREAD

**Issue by lianglinhuan** [didi/KnowStreaming#1149]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
knowstraming支持接入带kerberos认证的kafak集群吗？

**Comment by ZQKC** [comment]
> * [ ]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ## 在这里提出你的问题
> knowstraming支持接入带kerberos认证的kafak集群吗？

见faq

**Comment by lianglinhuan** [comment]
哥您好，faq是在哪里呢，可以说明下吗？您是否已经测试过kerberos的兼容了？ @ZQKC

**Comment by ZQKC** [comment]
> 哥您好，faq是在哪里呢，可以说明下吗？您是否已经测试过kerberos的兼容了？ @ZQKC

1、https://github.com/didi/KnowStreaming/blob/master/docs/user_guide/faq.md；
2、群里多个用户测试验证过，我这边没有测试过；

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue

**Comment by lianglinhuan** [comment]
我用这个链接访问好像没有内容，哥，您那边可以访问吗？

**Comment by ZQKC** [comment]
> 我用这个链接访问好像没有内容，哥，您那边可以访问吗？

最后的；去掉即可

**Comment by lianglinhuan** [comment]
@ZQKC 调整了几次Kerberos认证，但是都报下面这个错误，您可以帮忙看看是啥问题吗？


2023-10-10 18:20:08.586 ERROR 60649 --- [kTP-6-thread-12] c.x.k.s.k.c.s.g.impl.GroupServiceImpl    : method=listGroupsFromKafka||clusterPhyId=3||errMsg=exception!

org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
        at com.xiaojukeji.know.streaming.km.common.utils.kafka.KSPartialKafkaAdminClient.createInternal(KSPartialKafkaAdminClient.java:329)
        at com.xiaojukeji.know.streaming.km.common.utils.kafka.KSPartialKafkaAdminClient.create(KSPartialKafkaAdminClient.java:264)
        at com.xiaojukeji.know.streaming.km.core.service.group.impl.GroupServiceImpl.listGroupsFromKafka(GroupServiceImpl.java:82)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.SyncKafkaGroupTask.processClusterTask(SyncKafkaGroupTask.java:37)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.AbstractAsyncMetadataDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetadataDispatchTask.java:33)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at com.xiaojukeji.know.streaming.km.common.utils.kafka.KSPartialKafkaAdminClient.createInternal(KSPartialKafkaAdminClient.java:302)
        ... 9 common frames omitted
Caused by: javax.security.auth.login.LoginException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:917)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:737)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:592)
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
        at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
        at org.apache.kafka.common.security.kerberos.KerberosLogin.login(KerberosLogin.java:103)
        at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
        at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
        ... 13 common frames omitted

2023-10-10 18:20:08.586 ERROR 60649 --- [kTP-6-thread-12] .t.k.m.AbstractAsyncMetadataDispatchTask : method=asyncProcessSubTask||taskName=SyncKafkaGroupTask||clusterPhyId=3||errMsg=exception

com.xiaojukeji.know.streaming.km.common.exception.AdminOperateException: Failed to create new KafkaAdminClient
        at com.xiaojukeji.know.streaming.km.core.service.group.impl.GroupServiceImpl.listGroupsFromKafka(GroupServiceImpl.java:97)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.SyncKafkaGroupTask.processClusterTask(SyncKafkaGroupTask.java:37)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.AbstractAsyncMetadataDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetadataDispatchTask.java:33)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
        at com.xiaojukeji.know.streaming.km.common.utils.kafka.KSPartialKafkaAdminClient.createInternal(KSPartialKafkaAdminClient.java:329)
        at com.xiaojukeji.know.streaming.km.common.utils.kafka.KSPartialKafkaAdminClient.create(KSPartialKafkaAdminClient.java:264)
        at com.xiaojukeji.know.streaming.km.core.service.group.impl.GroupServiceImpl.listGroupsFromKafka(GroupServiceImpl.java:82)
        ... 7 common frames omitted
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at com.xiaojukeji.know.streaming.km.common.utils.kafka.KSPartialKafkaAdminClient.createInternal(KSPartialKafkaAdminClient.java:302)
        ... 9 common frames omitted
Caused by: javax.security.auth.login.LoginException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:917)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:737)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:592)
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
        at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
        at org.apache.kafka.common.security.kerberos.KerberosLogin.login(KerberosLogin.java:103)
        at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
        at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
        ... 13 common frames omitted

2023-10-10 18:20:08.629  INFO 60649 --- [kTP-6-thread-18] c.x.k.s.k.c.u.z.FourLetterWordUtil       : connecting to gci-kafka-1.gci-china.com 2181
2023-10-10 18:20:08.631 ERROR 60649 --- [kTP-6-thread-19] c.x.k.s.k.p.k.z.s.impl.KafkaZKDAOImpl    : method=getChildren||clusterPhyId=3||path=/brokers/ids||errMsg=exception

org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2746)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2772)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl.getChildren(KafkaZKDAOImpl.java:181)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl$$FastClassBySpringCGLIB$$6e05ff5c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.xiaojukeji.know.streaming.km.persistence.kafka.zookeeper.service.impl.KafkaZKDAOImpl$$EnhancerBySpringCGLIB$$ca316c02.getChildren(<generated>)
        at com.xiaojukeji.know.streaming.km.core.service.broker.impl.BrokerServiceImpl.getBrokersFromZKClient(BrokerServiceImpl.java:326)
        at com.xiaojukeji.know.streaming.km.core.service.broker.impl.BrokerServiceImpl.listBrokersFromKafka(BrokerServiceImpl.java:104)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.SyncBrokerTask.processClusterTask(SyncBrokerTask.java:30)
        at com.xiaojukeji.know.streaming.km.task.kafka.metadata.AbstractAsyncMetadataDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetadataDispatchTask.java:33)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

2023-10-10 18:20:08.632 ERROR 60649 --- [kTP-6-thread-19] c.x.k.s.k.c.s.b.impl.BrokerServiceImpl   : method=getBrokersFromZKClient||clusterPhyId=3||errMsg=exception
