### ISSUE TITLE
为什么knowstream原先是正常，跑几天后会有一个404的报错呢？

### ISSUE THREAD

**Issue by lianglinhuan** [didi/KnowStreaming#1214]
ERROR 3860537 --- [Pool-6-thread-7] errorLogger                              : method=doQuery||indexName=[ks_kafka_topic_metric_2024-01-11,ks_kafka_topic_metric_2024-01-12]||queryDsl={"query":{"bool":{"must":[{"term":{"clusterPhyId":{"value":2}}},{"term":{"topic":{"value":"wyc_history_gps"}}},{"term":{"brokerAgg":{"value":"1"}}},{"range":{"timestamp":{"gte":1705021680351,"lte":1705022280351}}}],"must_not":[{"term":{"metrics.PartitionURP":{"value":0.0}}}]}}}||errMsg=query error.

com.didiglobal.logi.elasticsearch.client.model.exception.ESIndexNotFoundException: method [GET], host [http://127.0.0.1:8060], URI [/ks_kafka_topic_metric_2024-01-11,ks_kafka_topic_metric_2024-01-12/_search?routing=wyc_history_gps], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ks_kafka_topic_metric_2024-01-11]","resource.type":"index_or_alias","resource.id":"ks_kafka_topic_metric_2024-01-11","index_uuid":"_na_","index":"ks_kafka_topic_metric_2024-01-11"}],"type":"index_not_found_exception","reason":"no such index [ks_kafka_topic_metric_2024-01-11]","resource.type":"index_or_alias","resource.id":"ks_kafka_topic_metric_2024-01-11","index_uuid":"_na_","index":"ks_kafka_topic_metric_2024-01-11"},"status":404}
        at com.didiglobal.logi.elasticsearch.client.model.exception.ExceptionFactory.translate(ExceptionFactory.java:7)
        at com.didiglobal.logi.elasticsearch.client.ESClient$1.onFailure(ESClient.java:270)
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:853)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:556)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:533)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
        at org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ZQKC** [comment]
> ERROR 3860537 --- [Pool-6-thread-7] errorLogger : method=doQuery||indexName=[ks_kafka_topic_metric_2024-01-11,ks_kafka_topic_metric_2024-01-12]||queryDsl={"query":{"bool":{"must":[{"term":{"clusterPhyId":{"value":2}}},{"term":{"topic":{"value":"wyc_history_gps"}}},{"term":{"brokerAgg":{"value":"1"}}},{"range":{"timestamp":{"gte":1705021680351,"lte":1705022280351}}}],"must_not":[{"term":{"metrics.PartitionURP":{"value":0.0}}}]}}}||errMsg=query error.
> 
> com.didiglobal.logi.elasticsearch.client.model.exception.ESIndexNotFoundException: method [GET], host [http://127.0.0.1:8060], URI [/ks_kafka_topic_metric_2024-01-11,ks_kafka_topic_metric_2024-01-12/_search?routing=wyc_history_gps], status line [HTTP/1.1 404 Not Found] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ks_kafka_topic_metric_2024-01-11]","resource.type":"index_or_alias","resource.id":"ks_kafka_topic_metric_2024-01-11","index_uuid":"_na_","index":"ks_kafka_topic_metric_2024-01-11"}],"type":"index_not_found_exception","reason":"no such index [ks_kafka_topic_metric_2024-01-11]","resource.type":"index_or_alias","resource.id":"ks_kafka_topic_metric_2024-01-11","index_uuid":"_na_","index":"ks_kafka_topic_metric_2024-01-11"},"status":404} at com.didiglobal.logi.elasticsearch.client.model.exception.ExceptionFactory.translate(ExceptionFactory.java:7) at com.didiglobal.logi.elasticsearch.client.ESClient$1.onFailure(ESClient.java:270) at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:853) at org.elasticsearch.client.RestClient$1.completed(RestClient.java:556) at org.elasticsearch.client.RestClient$1.completed(RestClient.java:533) at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181) at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) at org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83) at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) at java.base/java.lang.Thread.run(Thread.java:834)

1、es集群是否正常？可以先看看页面无数据排查文档。
2、如果这个错误每天凌晨短暂出现，那么应该是一个需要优化的地方。
