### ISSUE TITLE
knowstreaming搜集不到Zookeeper的部分指标

### ISSUE THREAD

**Issue by kaolaaz163** [didi/KnowStreaming#1218]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题

knowstreaming搜集不到Zookeeper的部分指标，环境信息如下：

Zookeeper：3.8.3
Kafka：3.6.1
Java：1.8.0_391-b13
KS：3.3.0

knowstreaming-manager容器的报错信息如下：

```
2024-01-30 13:03:51.760 ERROR 12 --- [kTP-5-thread-12] x.k.s.k.c.b.e.z.f.p.MonitorCmdDataParser : method=parseAndInitData||clusterPhyId=1||host=192.168.3.140||port=2181||name=zk_packets_received||value=7004.0||errMsg=exception!

java.lang.NumberFormatException: For input string: "7004.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.lambda$parseAndInitData$0(MonitorCmdDataParser.java:70)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:54)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:30)
	at com.xiaojukeji.know.streaming.km.common.utils.zookeeper.FourLetterWordUtil.executeFourLetterCmd(FourLetterWordUtil.java:56)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:234)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2024-01-30 13:03:51.761 ERROR 12 --- [kTP-5-thread-12] x.k.s.k.c.b.e.z.f.p.MonitorCmdDataParser : method=parseAndInitData||clusterPhyId=1||host=192.168.3.140||port=2181||name=zk_max_file_descriptor_count||value=4096.0||errMsg=exception!

java.lang.NumberFormatException: For input string: "4096.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.lambda$parseAndInitData$0(MonitorCmdDataParser.java:100)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:54)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:30)
	at com.xiaojukeji.know.streaming.km.common.utils.zookeeper.FourLetterWordUtil.executeFourLetterCmd(FourLetterWordUtil.java:56)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:234)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2024-01-30 13:03:51.761 ERROR 12 --- [kTP-5-thread-12] x.k.s.k.c.b.e.z.f.p.MonitorCmdDataParser : method=parseAndInitData||clusterPhyId=1||host=192.168.3.140||port=2181||name=zk_outstanding_requests||value=0.0||errMsg=exception!

java.lang.NumberFormatException: For input string: "0.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.lambda$parseAndInitData$0(MonitorCmdDataParser.java:79)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:54)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:30)
	at com.xiaojukeji.know.streaming.km.common.utils.zookeeper.FourLetterWordUtil.executeFourLetterCmd(FourLetterWordUtil.java:56)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:234)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


2024-01-30 13:03:51.762 ERROR 12 --- [kTP-5-thread-12] x.k.s.k.c.b.e.z.f.p.MonitorCmdDataParser : method=parseAndInitData||clusterPhyId=1||host=192.168.3.140||port=2181||name=zk_ephemerals_count||value=4.0||errMsg=exception!

java.lang.NumberFormatException: For input string: "4.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.lambda$parseAndInitData$0(MonitorCmdDataParser.java:91)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:54)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:30)
	at com.xiaojukeji.know.streaming.km.common.utils.zookeeper.FourLetterWordUtil.executeFourLetterCmd(FourLetterWordUtil.java:56)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:234)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


2024-01-30 13:03:51.763 ERROR 12 --- [kTP-5-thread-12] x.k.s.k.c.b.e.z.f.p.MonitorCmdDataParser : method=parseAndInitData||clusterPhyId=1||host=192.168.3.140||port=2181||name=zk_approximate_data_size||value=18771.0||errMsg=exception!

java.lang.NumberFormatException: For input string: "18771.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.lambda$parseAndInitData$0(MonitorCmdDataParser.java:94)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:54)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:30)
	at com.xiaojukeji.know.streaming.km.common.utils.zookeeper.FourLetterWordUtil.executeFourLetterCmd(FourLetterWordUtil.java:56)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:234)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2024-01-30 13:03:51.765 ERROR 12 --- [kTP-5-thread-12] x.k.s.k.c.b.e.z.f.p.MonitorCmdDataParser : method=parseAndInitData||clusterPhyId=1||host=192.168.3.140||port=2181||name=zk_num_alive_connections||value=5.0||errMsg=exception!

java.lang.NumberFormatException: For input string: "5.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.lambda$parseAndInitData$0(MonitorCmdDataParser.java:76)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:54)
	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:30)
	at com.xiaojukeji.know.streaming.km.common.utils.zookeeper.FourLetterWordUtil.executeFourLetterCmd(FourLetterWordUtil.java:56)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:234)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


2024-01-30 13:03:51.766 ERROR 12 --- [kTP-5-thread-12] c.x.k.s.k.c.m.k.ZookeeperMetricCollector : method=collectMetrics||clusterPhyId=1||metricName=WatchCount||errMsg=exception!

java.lang.NullPointerException: null
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:260)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2024-01-30 13:03:51.766  INFO 12 --- [kTP-5-thread-12] .x.k.s.k.c.s.v.BaseVersionControlService : method=doVCHandler||clusterId=1||action=EphemeralsCount||type=ZookeeperMetric||param={"clusterPhyId":1,"kafkaControllerId":0,"metricName":"EphemeralsCount","zkAddressList":[{"v1":"192.168.3.140","v2":2181},{"v1":"192.168.3.141","v2":2181},{"v1":"192.168.3.142","v2":2181}]}
2024-01-30 13:03:51.766 ERROR 12 --- [kTP-5-thread-12] c.x.k.s.k.c.m.k.ZookeeperMetricCollector : method=collectMetrics||clusterPhyId=1||metricName=EphemeralsCount||errMsg=exception!

java.lang.NullPointerException: null
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:260)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2024-01-30 13:03:51.766  INFO 12 --- [kTP-5-thread-12] .x.k.s.k.c.s.v.BaseVersionControlService : method=doVCHandler||clusterId=1||action=ApproximateDataSize||type=ZookeeperMetric||param={"clusterPhyId":1,"kafkaControllerId":0,"metricName":"ApproximateDataSize","zkAddressList":[{"v1":"192.168.3.140","v2":2181},{"v1":"192.168.3.141","v2":2181},{"v1":"192.168.3.142","v2":2181}]}
2024-01-30 13:03:51.766 ERROR 12 --- [kTP-5-thread-12] c.x.k.s.k.c.m.k.ZookeeperMetricCollector : method=collectMetrics||clusterPhyId=1||metricName=ApproximateDataSize||errMsg=exception!

java.lang.NullPointerException: null
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:260)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2024-01-30 13:03:51.766  INFO 12 --- [kTP-5-thread-12] .x.k.s.k.c.s.v.BaseVersionControlService : method=doVCHandler||clusterId=1||action=OpenFileDescriptorCount||type=ZookeeperMetric||param={"clusterPhyId":1,"kafkaControllerId":0,"metricName":"OpenFileDescriptorCount","zkAddressList":[{"v1":"192.168.3.140","v2":2181},{"v1":"192.168.3.141","v2":2181},{"v1":"192.168.3.142","v2":2181}]}
2024-01-30 13:03:51.766 ERROR 12 --- [kTP-5-thread-12] c.x.k.s.k.c.m.k.ZookeeperMetricCollector : method=collectMetrics||clusterPhyId=1||metricName=OpenFileDescriptorCount||errMsg=exception!

java.lang.NullPointerException: null
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:260)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2024-01-30 13:03:51.766  INFO 12 --- [kTP-5-thread-12] .x.k.s.k.c.s.v.BaseVersionControlService : method=doVCHandler||clusterId=1||action=MaxFileDescriptorCount||type=ZookeeperMetric||param={"clusterPhyId":1,"kafkaControllerId":0,"metricName":"MaxFileDescriptorCount","zkAddressList":[{"v1":"192.168.3.140","v2":2181},{"v1":"192.168.3.141","v2":2181},{"v1":"192.168.3.142","v2":2181}]}
2024-01-30 13:03:51.767 ERROR 12 --- [kTP-5-thread-12] c.x.k.s.k.c.m.k.ZookeeperMetricCollector : method=collectMetrics||clusterPhyId=1||metricName=MaxFileDescriptorCount||errMsg=exception!

java.lang.NullPointerException: null
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:260)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.ZookeeperMetricCollector.collectKafkaMetrics(ZookeeperMetricCollector.java:86)
	at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:25)
	at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

KnowStreaming页面上Zookeeper部分指标没有数据：

![1](https://github.com/didi/KnowStreaming/assets/151839092/d03ccf22-894f-4a1d-af64-ff592926408a)

**Comment by ZQKC** [comment]
使用最新版本看一下看能否解决该问题，最新版本修复了一个ZK四字命令的解析问题。
