### ISSUE TITLE
脚本离线安装，为什么重启knowstream原先的集群的数据采集会有问题呢？

### ISSUE THREAD

**Issue by lianglinhuan** [didi/KnowStreaming#1243]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
脚本离线安装，为什么重启knowstream原先的集群的数据采集会有问题呢？我得版本是3.3.0

**Comment by lianglinhuan** [comment]
在KnowStreaming/bin目录下了执行./shutdown.sh然后进行./startup.sh重启，后出现报错
ERROR 53531 --- [skTP-5-thread-7] c.x.k.s.km.common.utils.FutureWaitUtil   : method=stepWaitResult||taskName=class=HealthCheckTopicService||method=calAndUpdateHealthCheckResult||clusterId=17||errMsg=exception

java.util.concurrent.TimeoutException: null
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at com.xiaojukeji.know.streaming.km.common.utils.FutureWaitUtil.stepWaitResult(FutureWaitUtil.java:155)
        at com.xiaojukeji.know.streaming.km.common.utils.FutureWaitUtil.waitResult(FutureWaitUtil.java:116)
        at com.xiaojukeji.know.streaming.km.common.utils.FutureWaitUtil.waitExecute(FutureWaitUtil.java:76)
        at com.xiaojukeji.know.streaming.km.task.kafka.health.AbstractHealthCheckTask.calAndUpdateHealthCheckResult(AbstractHealthCheckTask.java:64)
        at com.xiaojukeji.know.streaming.km.task.kafka.health.AbstractHealthCheckTask.processClusterTask(AbstractHealthCheckTask.java:35)
        at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
