### ISSUE TITLE
问题求解，无法连接消费者组

### ISSUE THREAD

**Issue by lslone** [didi/KnowStreaming#459]
2022-02-08 11:42:15.164 [pool-16-thread-3] ERROR c.x.k.m.t.s.metadata.FlushBKConsumerGroupMetadata - collect consumerGroupSummary failed, clusterId:1 consumerGroup:connect-cluster.
java.lang.IllegalArgumentException: Consumer Group connect-cluster with protocol type 'connect' is not a valid consumer group
        at kafka.admin.AdminClient.describeConsumerGroup(AdminClient.scala:165)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.collectConsumerGroupSummary(FlushBKConsumerGroupMetadata.java:108)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.flush(FlushBKConsumerGroupMetadata.java:60)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.schedule(FlushBKConsumerGroupMetadata.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-02-08 11:43:15.156 [pool-16-thread-1] ERROR c.x.k.m.t.s.metadata.FlushBKConsumerGroupMetadata - collect consumerGroupSummary failed, clusterId:1 consumerGroup:schema-registry.
java.lang.IllegalArgumentException: Consumer Group schema-registry with protocol type 'sr' is not a valid consumer group
        at kafka.admin.AdminClient.describeConsumerGroup(AdminClient.scala:165)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.collectConsumerGroupSummary(FlushBKConsumerGroupMetadata.java:108)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.flush(FlushBKConsumerGroupMetadata.java:60)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.schedule(FlushBKConsumerGroupMetadata.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-02-08 11:43:15.171 [pool-16-thread-1] ERROR c.x.k.m.t.s.metadata.FlushBKConsumerGroupMetadata - collect consumerGroupSummary failed, clusterId:1 consumerGroup:connect-spider-cluster.
java.lang.IllegalArgumentException: Consumer Group connect-spider-cluster with protocol type 'connect' is not a valid consumer group

**Comment by lslone** [comment]
所做操作：按照教程安装后，只是做了修改了admin密码的操作。重刷后出现该错误
kafka版本：2.5.0

**Comment by lslone** [comment]
重启后恢复正常....

**Comment by lslone** [comment]
下游对接的是kafka connect的消费

**Comment by ZQKC** [comment]
> 下游对接的是kafka connect的消费

java.lang.IllegalArgumentException: Consumer Group connect-cluster with protocol type 'connect' is not a valid consumer group

LogiKM使用的Kafka客户端版本比较低导致的connect的消费组解析不了，后续3.0版本会进行解决

**Comment by ZQKC** [comment]
3.x版本升级了Kafka-Client，该问题已解决，可以尝鲜使用一下～
