### ISSUE TITLE
消费者信息获取失败，LogiKM 2.6.0

### ISSUE THREAD

**Issue by zhushanwei** [didi/KnowStreaming#491]
022-05-25 11:30:30.020 [pool-20-thread-15] ERROR c.x.k.manager.task.component.AbstractScheduledTask - customScheduled task running, but without registrant, and so sch
eduled tasks can't execute, scheduledName:newCollectAndPublishCGData.
2022-05-25 11:31:15.136 [pool-20-thread-11] ERROR c.x.kafka.manager.service.cache.KafkaClientPool - create kafka admin client failed, clusterId:2.
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at scala.collection.convert.Wrappers$JPropertiesWrapper$$anon$3.next(Wrappers.scala:459)
        at scala.collection.convert.Wrappers$JPropertiesWrapper$$anon$3.next(Wrappers.scala:454)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce$class.toMap(TraversableOnce.scala:279)
        at scala.collection.AbstractTraversable.toMap(Traversable.scala:105)
        at kafka.admin.AdminClient$.create(AdminClient.scala:221)
        at kafka.admin.AdminClient.create(AdminClient.scala)
        at com.xiaojukeji.kafka.manager.service.cache.KafkaClientPool.getAdminClient(KafkaClientPool.java:188)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.collectAndSaveConsumerGroup(FlushBKConsumerGroupMetadata.java:78)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.flush(FlushBKConsumerGroupMetadata.java:55)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.schedule(FlushBKConsumerGroupMetadata.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-05-25 11:31:15.137 [pool-20-thread-11] ERROR c.x.k.m.t.s.metadata.FlushBKConsumerGroupMetadata - collect consumerGroup failed, clusterId:2.
java.lang.NullPointerException: null
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.collectAndSaveConsumerGroup(FlushBKConsumerGroupMetadata.java:80)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.flush(FlushBKConsumerGroupMetadata.java:55)
        at com.xiaojukeji.kafka.manager.task.schedule.metadata.FlushBKConsumerGroupMetadata.schedule(FlushBKConsumerGroupMetadata.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by zhushanwei** [comment]
这是偶发性异常

**Comment by ZQKC** [comment]
> 这是偶发性异常

Topic的详情 -》分区信息 中的offset信息是否可以正常展示？看着是创建AdminClient的时候出现类型转换错误，方便的话，能否给一下2这个集群在cluster表中的数据。

**Comment by ZQKC** [comment]
无更多反馈，关闭该Issue
