### ISSUE TITLE
3.0.0接入服务空指针异常

### ISSUE THREAD

**Issue by Huyueeer** [didi/KnowStreaming#530]
接入3.0.0之后发现每点击一个页面就会发现红框：服务空指针异常，起初以为是我们集群的事，就心部署了一个测试集群，发现还是依据；
Kafka版本：confluentinc/cp-kafka:5.5.2 
空指针报错下面没堆栈，上面会有Es的404：
```shell
knowstreaming    | 2022-08-31 10:41:30.126 ERROR 6 --- [nio-9097-exec-4] errorLogger                              : method=doQuery||indexName=[ks_kafka_cluster_metric_2022-08-30,ks_kafka_cluster_metric_2022-08-31]||queryDsl={"_source":"timestamp","size":1,"query":{"bool":{"must":[{"range":{"timestamp":{"gte":1661870490097,"lte":1661913690097}}},{"term":{"clusterPhyId":{"value":10}}}]}},"sort":[{"timestamp":{"order":"desc"}}]}||errMsg=query error.
knowstreaming    |
knowstreaming    | com.didiglobal.logi.elasticsearch.client.model.exception.ESIndexNotFoundException: method [GET], host [http://10.191.7.17:9200], URI [/ks_kafka_cluster_metric_2022-08-30,ks_kafka_cluster_metric_2022-08-31/_search], status line [HTTP/1.1 404 Not Found]
knowstreaming    | {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ks_kafka_cluster_metric_2022-08-31]","resource.type":"index_or_alias","resource.id":"ks_kafka_cluster_metric_2022-08-31","index_uuid":"_na_","index":"ks_kafka_cluster_metric_2022-08-31"}],"type":"index_not_found_exception","reason":"no such index [ks_kafka_cluster_metric_2022-08-31]","resource.type":"index_or_alias","resource.id":"ks_kafka_cluster_metric_2022-08-31","index_uuid":"_na_","index":"ks_kafka_cluster_metric_2022-08-31"},"status":404}
knowstreaming    |      at com.didiglobal.logi.elasticsearch.client.model.exception.ExceptionFactory.translate(ExceptionFactory.java:7)
knowstreaming    |      at com.didiglobal.logi.elasticsearch.client.ESClient$1.onFailure(ESClient.java:270)
knowstreaming    |      at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:853)
knowstreaming    |      at org.elasticsearch.client.RestClient$1.completed(RestClient.java:556)
knowstreaming    |      at org.elasticsearch.client.RestClient$1.completed(RestClient.java:533)
knowstreaming    |      at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
knowstreaming    |      at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
knowstreaming    |      at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
knowstreaming    |      at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
knowstreaming    |      at org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
knowstreaming    |      at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
knowstreaming    |      at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
knowstreaming    |      at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
knowstreaming    |      at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
knowstreaming    |      at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
knowstreaming    |      at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
knowstreaming    |      at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
knowstreaming    |      at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
knowstreaming    |      at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
knowstreaming    |      at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
knowstreaming    |      at java.base/java.lang.Thread.run(Thread.java:829)
knowstreaming    |
knowstreaming    | 2022-08-31 10:41:30.126 ERROR 6 --- [nio-9097-exec-4] x.k.s.k.r.h.CustomGlobalExceptionHandler : method=handleNullPointerException||errMsg=exception
knowstreaming    |
knowstreaming    | java.lang.NullPointerException: null
knowstreaming    |
```
还有些日志
```shell
knowstreaming    | java.lang.NullPointerException: null
knowstreaming    |      at com.xiaojukeji.know.streaming.km.persistence.es.dao.BaseMetricESDAO.lambda$getLatestMetricTime$1(BaseMetricESDAO.java:361)
knowstreaming    |      at com.xiaojukeji.know.streaming.km.persistence.es.ESOpClient.performRequest(ESOpClient.java:174)
knowstreaming    |      at com.xiaojukeji.know.streaming.km.persistence.es.dao.BaseMetricESDAO.getLatestMetricTime(BaseMetricESDAO.java:361)
knowstreaming    |      at com.xiaojukeji.know.streaming.km.persistence.es.dao.BaseMetricESDAO.getLatestMetricTime(BaseMetricESDAO.java:345)
knowstreaming    |      at com.xiaojukeji.know.streaming.km.persistence.es.dao.ClusterMetricESDAO.getClusterLatestMetrics(ClusterMetricESDAO.java:43)
knowstreaming    |      at com.xiaojukeji.know.streaming.km.core.service.cluster.impl.ClusterMetricServiceImpl.getLatestMetricsFromES(ClusterMetricServiceImpl.java:279)
knowstreaming    |      at com.xiaojukeji.know.streaming.km.rest.api.v3.cluster.ClusterMetricsController.getLatestClusterMetrics(ClusterMetricsController.java:43)
knowstreaming    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
knowstreaming    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
knowstreaming    |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
knowstreaming    |      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
knowstreaming    |      at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
knowstreaming    |      at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
knowstreaming    |      at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
knowstreaming    |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
knowstreaming    |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
knowstreaming    |      at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
knowstreaming    |      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
knowstreaming    |      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
knowstreaming    |      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
knowstreaming    |      at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
knowstreaming    |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
knowstreaming    |      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
knowstreaming    |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
knowstreaming    |      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
knowstreaming    |      at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
knowstreaming    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
knowstreaming    |      at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
knowstreaming    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
knowstreaming    |      at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
knowstreaming    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
knowstreaming    |      at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
knowstreaming    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
knowstreaming    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
knowstreaming    |      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
knowstreaming    |      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
knowstreaming    |      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
knowstreaming    |      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
knowstreaming    |      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
knowstreaming    |      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
knowstreaming    |      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
knowstreaming    |      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
knowstreaming    |      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
knowstreaming    |      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
knowstreaming    |      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
knowstreaming    |      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
knowstreaming    |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
knowstreaming    |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
knowstreaming    |      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
knowstreaming    |      at java.base/java.lang.Thread.run(Thread.java:829)
knowstreaming    |
```

**Comment by ZQKC** [comment]
需要初始化一下ES近7天的索引，详细见 https://github.com/didi/KnowStreaming/blob/master/bin/init_es_template.sh 末尾的初始化shell

**Comment by Huyueeer** [comment]
> 需要初始化一下ES近7天的索引，详细见 https://github.com/didi/KnowStreaming/blob/master/bin/init_es_template.sh 末尾的初始化shell

这个我已经执行了，过程也没有报错，Elastic里面也存在index，但是我发现没有存在今天8.31的ks_kafka_topic_metric_2022-08-31

**Comment by ZQKC** [comment]
> > 需要初始化一下ES近7天的索引，详细见 https://github.com/didi/KnowStreaming/blob/master/bin/init_es_template.sh 末尾的初始化shell
> 
> 这个我已经执行了，过程也没有报错，Elastic里面也存在index，但是我发现没有存在今天8.31的ks_kafka_topic_metric_2022-08-31

可以检查一下：
1、今天KS是否有指标数据写入ES，如果没有则今天的索引会不存在；
2、KS将指标数据写入ES的时候，是否有什么错误；
3、ES集群的磁盘等空间是不是正常的；

**Comment by ZQKC** [comment]
后续可以考虑升级至最新版本，当前无更多反馈，关闭该Issue，

**Comment by zhaoli2333** [comment]
我也遇到这个问题，可能是之前有一段时间磁盘满了不可用导致的。但是后面清理了磁盘也无法恢复

**Comment by ZQKC** [comment]
> 我也遇到这个问题，可能是之前有一段时间磁盘满了不可用导致的。但是后面清理了磁盘也无法恢复。直到删除es数据，重启es，重新执行init脚本后恢复

可以看一下是不是es的shard满了导致的

**Comment by nidonglin** [comment]
默认elasticsearch7版本以上的分片数默认值是1000，看下log/es.log下有没有类似这种错误“Validation Failed: 1: this action would add [4] total shards, but this cluster currently has [998]/[1000]”,如果有则需要扩容一下；
执行命令： curl -X PUT {your es ip}:9200/_cluster/settings -H "Content-Type: application/json" -d '{ "persistent": { "cluster.max_shards_per_node": "10000" } }'
