### ISSUE TITLE
errorLogger     : method=handleESQueryResponse||metric=TotalLogSize||errMsg=exception!

### ISSUE THREAD

**Issue by simple-cmd** [didi/KnowStreaming#570]
2022-09-09 16:46:58.376 ERROR 1 --- [SDAO-3-thread-8] errorLogger                              : method=handleESQueryResponse||metric=TotalLogSize||errMsg=exception!

java.lang.NullPointerException: null
	at com.xiaojukeji.know.streaming.km.persistence.es.dao.ClusterMetricESDAO.lambda$handleListESQueryResponse$3(ClusterMetricESDAO.java:197)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.xiaojukeji.know.streaming.km.persistence.es.dao.ClusterMetricESDAO.handleListESQueryResponse(ClusterMetricESDAO.java:193)
	at com.xiaojukeji.know.streaming.km.persistence.es.dao.ClusterMetricESDAO.lambda$null$1(ClusterMetricESDAO.java:140)
	at com.xiaojukeji.know.streaming.km.persistence.es.ESOpClient.performRequestWithRouting(ESOpClient.java:237)
	at com.xiaojukeji.know.streaming.km.persistence.es.dao.ClusterMetricESDAO.lambda$listClusterMetricsByClusterIds$2(ClusterMetricESDAO.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ZQKC** [comment]
Jmx是否正常开启？集群详情中，Cluster-Dashboard的MessagesIn指标是否非0？
