### ISSUE TITLE
增加集群成功，但是无法增删topic

### ISSUE THREAD

**Issue by leo432097** [didi/KnowStreaming#577]
kafka 版本 2.12-2.1.1 单节点集群，zookeeper-3.6.3 ,knowStreaming 为helm 安装。
server.properties如下
`broker.id=0
listeners=SASL_PLAINTEXT://192.168.0.2:9092
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism.inter.broker.protocol=PLAIN
sasl.enabled.mechanisms=PLAIN
advertised.listeners=SASL_PLAINTEXT://192.168.0.2:9092
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=/tmp/kafka-logs
num.partitions=1
num.recovery.threads.per.data.dir=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
zookeeper.connect=192.168.0.2:2181
zookeeper.connection.timeout.ms=6000
group.initial.rebalance.delay.ms=0
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
allow.everyone.if.no.acl.found=true
super.users=User:admin`
**通过页面添加kafka 集群成功，可以正常显示相关内容，但是通过页面修改topic, 后台直接报错timeout** 
2022-09-13 18:33:25.098 ERROR 1 --- [rd-1-8-thread-8] errorLogger                              : class=PartitionServiceImpl||method=getPartitionOffsetFromKafkaAdminClient||clusterPhyId=3||topicName=mytest||errMsg=exception!
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=metadata, deadlineMs=1663065205097, tries=1, nextAllowedTryMs=1663065205198) timed out at 1663065205098 after 1 attempt(s)
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at com.xiaojukeji.know.streaming.km.core.service.partition.impl.PartitionServiceImpl.getPartitionOffsetFromKafkaAdminClient(PartitionServiceImpl.java:297)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:90)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.partition.impl.PartitionServiceImpl.getPartitionOffsetFromKafka(PartitionServiceImpl.java:210)
	at com.xiaojukeji.know.streaming.km.core.service.partition.impl.PartitionMetricServiceImpl.getOffsetRelevantMetrics(PartitionMetricServiceImpl.java:180)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:90)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.partition.impl.PartitionMetricServiceImpl.collectPartitionsMetricsFromKafka(PartitionMetricServiceImpl.java:146)
	at com.xiaojukeji.know.streaming.km.core.service.partition.impl.PartitionMetricServiceImpl.collectPartitionsMetricsFromKafkaWithCache(PartitionMetricServiceImpl.java:85)
	at com.xiaojukeji.know.streaming.km.collector.metric.PartitionMetricCollector.collectMetrics(PartitionMetricCollector.java:94)
	at com.xiaojukeji.know.streaming.km.collector.metric.PartitionMetricCollector.lambda$collectMetrics$0(PartitionMetricCollector.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=metadata, deadlineMs=1663065205097, tries=1, nextAllowedTryMs=1663065205198) timed out at 1663065205098 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: metadata

自己通过kafka 客户端 增删改查topic 是没有问题，辛苦大佬查看一下。

**Comment by ZQKC** [comment]
接入集群时，进行的集群配置是？辛苦贴一下集群地址，ZK地址，集群配置那三块地方

**Comment by leo432097** [comment]
![1663122211796](https://user-images.githubusercontent.com/18698586/190044420-9facba9d-e194-48db-8899-06b2817c57fa.png)
zk, kafka  集群都是同一个IP 地址192.168.0.2，

**Comment by ZQKC** [comment]
集群本身开了SASL，但是在集群集群时，没有将认证信息配置上去，因此在获取集群信息时会失败～

**Comment by leo432097** [comment]
> 集群本身开了SASL，但是在集群集群时，没有将认证信息配置上去，因此在获取集群信息时会失败～

sasl认证账号信息在 Security 的Password Authentication 里设置了，平台可以获取打kafka 集群信息topic,user 等等，但是无法修改。之前kafka不开启sasl 认证时也是同样的问题。

**Comment by ZQKC** [comment]
> > 集群本身开了SASL，但是在集群集群时，没有将认证信息配置上去，因此在获取集群信息时会失败～
> 
> sasl认证账号信息在 Security 的Password Authentication 里设置了，平台可以获取打kafka 集群信息topic,user 等等，但是无法修改。之前kafka不开启sasl 认证时也是同样的问题。

那块是JMX的设置，SASL信息需要配置在“集群配置”中。上面那个错误，就是因为配置了错误的SASL信息导致的。

**Comment by leo432097** [comment]
> > > 集群本身开了SASL，但是在集群集群时，没有将认证信息配置上去，因此在获取集群信息时会失败～
> > 
> > 
> > sasl认证账号信息在 Security 的Password Authentication 里设置了，平台可以获取打kafka 集群信息topic,user 等等，但是无法修改。之前kafka不开启sasl 认证时也是同样的问题。
> 
> 那块是JMX的设置，SASL信息需要配置在“集群配置”中。上面那个错误，就是因为配置了错误的SASL信息导致的。

**集群设置添加：**
 {
  "security.protocol": "SASL_PLAINTEXT",
  "sasl.mechanisms": "DIGEST-MD5",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\"  password=\"admin-secret\";"
}
进行topic操作
**后台报错**
2022-09-16 20:47:37.793 ERROR 1 --- [p-nio-80-exec-1] c.x.k.s.k.p.kafka.KafkaAdminClient       : create kafka AdminClient failed, clusterPhyId:4 props:{bootstrap.servers=192.168.0.2:9092, sasl.mechanisms=DIGEST-MD5, sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin"  password="admin-secret";, security.protocol=SASL_PLAINTEXT}
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
  at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:540)
  at org.apache.kafka.clients.admin.Admin.create(Admin.java:134)
  at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
  at com.xiaojukeji.know.streaming.km.persistence.kafka.KafkaAdminClient.createKafkaAdminClient(KafkaAdminClient.java:105)
  at com.xiaojukeji.know.streaming.km.persistence.kafka.KafkaAdminClient.createKafkaAdminClient(KafkaAdminClient.java:87)
  at com.xiaojukeji.know.streaming.km.persistence.kafka.KafkaAdminClient.getClient(KafkaAdminClient.java:28)
  at com.xiaojukeji.know.streaming.km.core.service.topic.impl.OpTopicServiceImpl.deleteByKafkaClient(OpTopicServiceImpl.java:188)
  at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:90)
  at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
  at com.xiaojukeji.know.streaming.km.core.service.topic.impl.OpTopicServiceImpl.deleteTopic(OpTopicServiceImpl.java:133)
  at com.xiaojukeji.know.streaming.km.rest.api.v3.topic.TopicController.deleteTopics(TopicController.java:54)
  at sun.reflect.GeneratedMethodAccessor886.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
  at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:671)
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
  at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: No serviceName defined in either JAAS or Kafka config
  at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
  at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
  at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
  at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
  at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:513)
  ... 64 common frames omitted
Caused by: java.lang.IllegalArgumentException: No serviceName defined in either JAAS or Kafka config
  at org.apache.kafka.common.security.kerberos.KerberosLogin.getServiceName(KerberosLogin.java:303)
  at org.apache.kafka.common.security.kerberos.KerberosLogin.configure(KerberosLogin.java:92)
  at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:61)
  at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
  at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
  ... 68 common frames omitted

**kafka server的kafka_jaas.conf 配置如下**
`{
  "sasl.mechanisms": "PLAIN",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\"  password=\"admin-secret\",
  "security.protocol": "SASL_PLAINTEXT"
}

{
  "sasl.mechanisms": "PLAIN",
  "security.protocol": "SASL_PLAINTEXT",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\"  password=\"admin-secret\";"

}`
**在kafka 服务启动日志里 发现**
[2022-09-16 19:24:11,014] INFO Client will use DIGEST-MD5 as SASL mechanism. (org.apache.zookeeper.client.ZooKeeperSaslClient)
[2022-09-16 19:24:10,587] INFO Registered broker 0 at path /brokers/ids/0 with addresses: ArrayBuffer(EndPoint(192.168.0.2,9092,ListenerName(SAS_PLAINTEXT),SASL_PLAINTEXT)) (kafka.zk.KafkaZkClient)

在配置去掉  "sasl.mechanisms": "DIGEST-MD5",  报错依旧。

**Comment by ZQKC** [comment]
试一下这样填写：
```
{
  "sasl.mechanism": "PLAIN",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"aaa\" password=\"bbb\";",
  "security.protocol": "SASL_PLAINTEXT"
}
```

**Comment by leo432097** [comment]
> 试一下这样填写，将其中的aaa和bbb做相应的修改：
> 
> ```
> {
>   "sasl.mechanism": "PLAIN",
>   "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"aaa\" password=\"bbb\";",
>   "security.protocol": "SASL_PLAINTEXT"
> }
> ```

通过格式修改，和检查kafka_jaas.conf ，配置文件，问题解决了， 感谢支持。核心原因是jaas 的配置文件引号使用了中文

**Comment by ZQKC** [comment]
好的，有问题再随时交流～
