### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by haoqi123** [didi/KnowStreaming#662]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
有个相关的issue #582 异常输出原因都是`Deadlock`

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   v3.0</font>
* Operating System version :  <font size=4 color =red> Everything</font>
* Java version : <font size=4 color =red> Everything</font>

### 重现该问题的步骤

1. 项目运行一段时间后有几率出现该问题

---

如果有异常，请附上异常Trace:

```
2022-10-12 16:05:00.126 ERROR 13 --- [ool-6-thread-13] c.x.k.s.k.t.h.ClusterHealthCheckTask     : class=ClusterHealthCheckTask||method=processSubTask||clusterPhyId=1||checkResult=HealthCheckResult(dimension=0, configName=HC_CLUSTER_NO_CONTROLLER, clusterPhyId=1, resName=, passed=1)||errMsg=exception!

org.springframework.dao.DeadlockLoserDataAccessException: 
### Error updating database.  Cause: java.sql.SQLTransactionRollbackException: (conn=20) Deadlock found when trying to get lock; try restarting transaction
### The error may exist in URL [jar:file:/km-rest.jar!/BOOT-INF/lib/km-persistence-3.0.0.jar!/mybatis/HealthCheckResultMapper.xml]
### The error may involve com.xiaojukeji.know.streaming.km.persistence.mysql.health.HealthCheckResultDAO.replace-Inline
### The error occurred while setting parameters
### SQL: REPLACE ks_km_health_check_result         (dimension, config_name, cluster_phy_id, res_name, passed)         VALUES         (?, ?, ?, ?, ?)
### Cause: java.sql.SQLTransactionRollbackException: (conn=20) Deadlock found when trying to get lock; try restarting transaction
; (conn=20) Deadlock found when trying to get lock; try restarting transaction; nested exception is java.sql.SQLTransactionRollbackException: (conn=20) Deadlock found when trying to get lock; try restarting transaction
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:271)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy106.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy132.replace(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor651.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy133.replace(Unknown Source)
	at com.xiaojukeji.know.streaming.km.core.service.health.checkresult.impl.HealthCheckResultServiceImpl.replace(HealthCheckResultServiceImpl.java:33)
	at com.xiaojukeji.know.streaming.km.task.health.ClusterHealthCheckTask.calAndUpdateHealthCheckResult(ClusterHealthCheckTask.java:71)
	at com.xiaojukeji.know.streaming.km.task.health.ClusterHealthCheckTask.processClusterTask(ClusterHealthCheckTask.java:47)
	at com.xiaojukeji.know.streaming.km.task.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLTransactionRollbackException: (conn=20) Deadlock found when trying to get lock; try restarting transaction
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:294)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:819)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:758)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:677)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:620)
	at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:93)
	at org.mariadb.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:256)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy153.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at sun.reflect.GeneratedMethodAccessor413.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy151.update(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:56)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:85)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 25 common frames omitted
```

**Comment by dujingsong** [comment]
同样的情况，运行了一段时间后，希望能够尽快修复^_^
![image](https://user-images.githubusercontent.com/32673188/195481067-00b71ecf-400b-4960-93d4-0ccd0751e1da.png)
![image](https://user-images.githubusercontent.com/32673188/195481161-465afd6b-0957-4f2e-ba93-edba0c97675f.png)

**Comment by shirenchuang** [comment]
> 同样的情况，运行了一段时间后，希望能够尽快修复^_^ ![image](https://user-images.githubusercontent.com/32673188/195481067-00b71ecf-400b-4960-93d4-0ccd0751e1da.png) ![image](https://user-images.githubusercontent.com/32673188/195481161-465afd6b-0957-4f2e-ba93-edba0c97675f.png)

我们尽快确认一下

**Comment by RichardZhengkay** [comment]
I'll follow up on this issue.

**Comment by RichardZhengkay** [comment]
The issues has been fixed.
