### ISSUE TITLE
Ldap配置登录问题

### ISSUE THREAD

**Issue by SKYNE0** [didi/KnowStreaming#683]
### 环境信息
- CentOS7.X
- docker & docker-compose
- knowstreaming-manager:3.0.0
- knowstreaming/knowstreaming-manager:0.4.0
- OpenLdap

### 参考文档
- [登录系统对接](https://github.com/didi/KnowStreaming/blob/master/docs/dev_guide/%E7%99%BB%E5%BD%95%E7%B3%BB%E7%BB%9F%E5%AF%B9%E6%8E%A5.md)

### 问题描述
- 参考文档配置Ldap后，根据Openldap日志中的search结果看应该是正确搜索到了用户
- 感觉像是LdapAuthentication.java中getLdapAttrsInfo方法获取额外的字段时出现了异常
- 看源代码中获取额外的字段来填充用户信息，其中的字段在Openldap用户属性中并不存在

### 相关配置
```
# 节选
    resource-extend-bean-name: myResourceExtendImpl
    # login-extend-bean-name: logiSecurityDefaultLoginExtendImpl
    login-extend-bean-name: ksLdapLoginService

account:
  ldap:
    url: ldap://XXXXXX:389/
    basedn: ou=TechTeams,dc=xxxxxx,dc=com
    factory: com.sun.jndi.ldap.LdapCtxFactory
    filter: mail
    security:
      authentication: simple
      principal: cn=admin,dc=xxxxxxx,dc=com
      credentials: xxxxxxxxx
    auth-user-registration: true
    auth-user-registration-role: 1679
```

### 报错日志
```
# 节选
2022-10-14 12:24:39.305 ERROR 12 --- [p-nio-80-exec-1] c.x.k.s.k.a.l.l.r.LdapAuthentication     : method=getLdapAttrsInfo||userName=xxxxxxx.ma@xxxxxxx.com||errMsg=exception

java.lang.NullPointerException: null
        at com.xiaojukeji.know.streaming.km.account.login.ldap.remote.LdapAuthentication.getLdapAttrsInfo(LdapAuthentication.java:111)
        at com.xiaojukeji.know.streaming.km.account.login.ldap.remote.LdapAuthentication.authenticate(LdapAuthentication.java:40)
        at com.xiaojukeji.know.streaming.km.account.login.ldap.LdapLoginServiceImpl.verifyLogin(LdapLoginServiceImpl.java:62)
        at com.didiglobal.logi.security.service.impl.LoginServiceImpl.verifyLogin(LoginServiceImpl.java:24)
        at com.didiglobal.logi.security.controller.v1.LoginController.login(LoginController.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
```

### 相关截图
- 1. Openldap记录的搜索日志
![3205968d0d81e30206cbf27ba0ef9e0](https://user-images.githubusercontent.com/29617856/195762375-7f55bf06-5098-44b9-b00b-74be5f4d9e26.jpg)
- 2. 根据filter语句，自己使用ldapsearch的搜索结果
![image](https://user-images.githubusercontent.com/29617856/195762587-4afba900-9b81-4f32-a25d-92ed32ad2634.png)
- 3. 报错部分的源代码- 
![image](https://user-images.githubusercontent.com/29617856/195762809-b9ef806e-5c54-4f75-98c5-192f40f63832.png)

**Comment by ZQKC** [comment]
是一个BUG，这块不能直接.toString()，需要判断一下属性是否存在。老哥有兴趣的话，欢迎来个PR修复一下啊

**Comment by silent-night-no-trace** [comment]
1

**Comment by SKYNE0** [comment]
thanks
