### ISSUE TITLE
ServerCmdDataParser 解析 zookeeper 平均耗时异常

### ISSUE THREAD

**Issue by giraffe-tree** [didi/KnowStreaming#704]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.1.0 </font>
* Operating System version :  <font size=4 color =red> MacOS </font>
* Java version : <font size=4 color =red> 11 </font>
* Zookeeper version : <font size=4 color =red> 3.8.0-5a02a05eddb59aee6ac762f7ea82e92a68eb9c0f, built on 2022-02-25 08:49 UTC </font>

### 重现该问题的步骤

1. 使用 3.8.0 zookeeper , 启动 kafka 集群
2. 启动 knowstreaming
3. 使用 knowstreaming 接入该集群

### 预期结果

正常执行...

### 实际结果

在 ServerCmdDataParser L57 解析耗时时, 出现了 java.lang.NumberFormatException

```java
                    case "Latency min/avg/max":
                        String[] data = elem.getValue().split("/");
                        serverCmdData.setZkMinLatency(Long.valueOf(data[0]));
                        serverCmdData.setZkAvgLatency(Long.valueOf(data[1]));
                        serverCmdData.setZkMaxLatency(Long.valueOf(data[2]));
                        break;
```

<img width="600" alt="image" src="https://user-images.githubusercontent.com/26344661/196744815-bf4777b2-7381-4161-bfd5-9ccc0e9dcccc.png">

---

如果有异常，请附上异常Trace:

```
2022-10-19 23:54:00.450 ERROR 63994 --- [ool-6-thread-18] errorLogger                              : class=ZookeeperMetricCollector||method=collectMetrics||clusterPhyId=1||metricName=OutstandingRequests||errMsg=exception!

java.lang.NullPointerException: null
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromServerCmd(ZookeeperMetricServiceImpl.java:191)
	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:90)
	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:93)
	at com.xiaojukeji.know.streaming.km.collector.metric.ZookeeperMetricCollector.collectMetrics(ZookeeperMetricCollector.java:87)
	at com.xiaojukeji.know.streaming.km.task.metrics.ZookeeperMetricCollectorTask.processClusterTask(ZookeeperMetricCollectorTask.java:29)
	at com.xiaojukeji.know.streaming.km.task.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by giraffe-tree** [comment]
@shirenchuang 分给我吧

**Comment by ZQKC** [comment]
> @shirenchuang 分给我吧

master分支应该已经有同学将其修复了，辛苦看是否还存在

**Comment by giraffe-tree** [comment]
确实修复了
