### ISSUE TITLE
kafka集群Topic数量过多导致MetricCollector任务超时

### ISSUE THREAD

**Issue by zhaoli2333** [didi/KnowStreaming#726]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题
kafka集群有接近4000个topic，2500多个ConsumerGroup，很多MetricCollector任务超时，报错如下：

```
ERROR 28282 --- [Pool-7-thread-3] errorLogger : class=FutureUtil||method=stepWaitResult||taskName=method=TopicMetricCollector||clusterPhyId=1||topicName=xxxxxxxxxx||errMsg=exception 

java.util.concurrent.TimeoutException: null 
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) 
at com.xiaojukeji.know.streaming.km.common.utils.FutureWaitUtil.stepWaitResult(FutureWaitUtil.java:155) 
at com.xiaojukeji.know.streaming.km.common.utils.FutureWaitUtil.waitResult(FutureWaitUtil.java:116) 
at com.xiaojukeji.know.streaming.km.common.utils.FutureWaitUtil.waitExecute(FutureWaitUtil.java:76) 
at com.xiaojukeji.know.streaming.km.collector.metric.TopicMetricCollector.collectMetrics(TopicMetricCollector.java:73) 
at com.xiaojukeji.know.streaming.km.task.metrics.TopicMetricCollectorTask.processClusterTask(TopicMetricCollectorTask.java:29) 
at com.xiaojukeji.know.streaming.km.task.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33) 
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) 
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
at java.base/java.lang.Thread.run(Thread.java:834)
```

其他报错的任务包括：GroupMetricCollector，PartitionMetricCollector，TopicMetricCollector

求相关参数优化建议。

**Comment by ZQKC** [comment]
@zhaoli2333  老哥有兴趣，可以拉一下master最新的代码重新打包部署一下，看性能问题是否得到优化，有问题随时沟通。

**Comment by zhaoli2333** [comment]
> @zhaoli2333 老哥有兴趣，可以拉一下master最新的代码重新打包部署一下，看性能问题是否得到优化，有问题随时沟通。

拉了下master的代码，还是没有解决。

其实我之前自己优化过一波，超时的报错已经没有了，但是列表页的metric还是出不来，不知道为啥。

**Comment by ZQKC** [comment]
> @ZQKC 拉了下master的代码，还是没有解决。
> 
> 其实我之前自己优化过一波，思路就是每个集群创建一组AdminClient实例，优化后超时的报错已经没有了，但是列表页的metric还是出不来，不知道为啥。

1、看反馈，我理解超时问题是解决了，但是还存在其他问题是吧？
2、当前master分支也已具备创建一组AdminClient实例的功能，欢迎试用。
3、具体是哪些列表页面metric出不来呢？

**Comment by zhaoli2333** [comment]
@ZQKC topic列表页面的 Bytes In(KB/s) | Bytes Out(KB/s) | MessageSize(MB) 这三个数值出不来。（但趋势图能出来）

**Comment by ZQKC** [comment]
> @ZQKC topic列表页面的 Bytes In(KB/s) | Bytes Out(KB/s) | MessageSize(MB) 这三个数值出不来。（但趋势图能出来）

1、可以查询一下ES看一下最近5分钟指标是否存在，如果指标不存在，那么就是采集存在延迟。
2、如果在ES中存在该指标，那么需要看一下本地缓存的TopicMetrics指标是否正常。

集群比较大之后，AdminClient可能存在性能瓶颈，还有ESClient也可能存在，也需要看一下。master分支的代码对ESClient也进行了一些优化。

**Comment by zhaoli2333** [comment]
@ZQKC 查看了es的ks_kafka_topic_metric索引的metric字段，凡是有流量的topic，BytesIn_min_5、LogSize等字段是存在且有值的。但页面上单独查询该topic，/ks-km/api/v3/clusters/xx/topics-overview接口返回的latestMetrics.metrics字段为空

**Comment by ZQKC** [comment]
![image](https://user-images.githubusercontent.com/4694454/206114871-eb43e2ed-f56f-47ee-8b37-ae3b78378f33.png)

是这个原因导致的

**Comment by zhaoli2333** [comment]
@ZQKC 是的，刚debug了一下发现是这个原因，这里估计得分批

**Comment by ZQKC** [comment]
> @ZQKC 是的，刚debug了一下发现是这个原因，这里估计得分批

是的

**Comment by zhaoli2333** [comment]
@ZQKC 另外缓存size也得调大一些

**Comment by ZQKC** [comment]
> @ZQKC 另外缓存size也得调大一些

哪一个缓存的size？

**Comment by zhaoli2333** [comment]
@ZQKC DataBaseDataLocalCache.topicLatestMetricsCache

**Comment by zhaoli2333** [comment]
@ZQKC DataBaseDataLocalCache.topicLatestMetricsCache

**Comment by ZQKC** [comment]
> @ZQKC DataBaseDataLocalCache.topicLatestMetricsCache

key是集群ID，配置的是500，你们集群规模超过了500么，如果是的话，辛苦提个新的issue，后续调整为可配置的

**Comment by zhaoli2333** [comment]
@ZQKC 哦，看错了，抱歉

**Comment by ZQKC** [comment]
> @ZQKC 哦，看错了，抱歉

好的，相关问题已修复，关闭该Issue了～
