### ISSUE TITLE
分区数据迁移job一直处于doing状态

### ISSUE THREAD

**Issue by luckygqx** [didi/KnowStreaming#815]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.1.0</font>
* Operating System version :  <font size=4 color =red> docker linux</font>
* Java version : <font size=4 color =red> 8 </font>

### 重现该问题的步骤

指定主题分区数据迁移
![image](https://user-images.githubusercontent.com/57888095/205809901-d797a448-8313-4966-80bf-e51b50121e46.png)

### 预期结果
分区迁移完成后，job状态应置为成功。

### 实际结果
分区数据实际已经迁移成功，但job状态一直处于运行中
![image](https://user-images.githubusercontent.com/57888095/205810006-b6e77f6e-07b0-4a07-9ec6-9fa0c823766d.png)
![image](https://user-images.githubusercontent.com/57888095/205828420-8a453d19-f8e3-4118-a1ae-ff677a0bd209.png)

实际已经迁移成功
![image](https://user-images.githubusercontent.com/57888095/205835003-644e1eff-40fc-42a0-9688-6d6bdc52c153.png)

发现未存在/reassign_partitions子节点
![image](https://user-images.githubusercontent.com/57888095/205834582-db78e82e-e91d-4da2-8611-018cb3bb01ce.png)
---

如果有异常，请附上异常Trace:

好像是某个定时任务处理逻辑异常导致的，一分钟一次触发一次

![image](https://user-images.githubusercontent.com/57888095/205831415-73141a81-244d-4727-bf41-8b33b5777247.png)

![image](https://user-images.githubusercontent.com/57888095/205831486-f36ce7de-e147-4535-9f73-5a0fb8756eac.png)

![image](https://user-images.githubusercontent.com/57888095/205831227-c4904027-f5e3-41b8-8f0d-514d534393df.png)

```
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.ElectionNotNeededException: Leader election not needed for topic partition.
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
        at com.xiaojukeji.know.streaming.km.core.service.partition.impl.OpPartitionServiceImpl.preferredReplicaElectionByKafkaClient(OpPartitionServiceImpl.java:107)
        at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:90)
        at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
        at com.xiaojukeji.know.streaming.km.core.service.partition.impl.OpPartitionServiceImpl.preferredReplicaElection(OpPartitionServiceImpl.java:64)
        at com.xiaojukeji.know.streaming.km.core.service.reassign.impl.ReassignJobServiceImpl.preferredReplicaElection(ReassignJobServiceImpl.java:512)
        at com.xiaojukeji.know.streaming.km.core.service.reassign.impl.ReassignJobServiceImpl.verifyAndUpdateStatue(ReassignJobServiceImpl.java:393)
        at com.xiaojukeji.know.streaming.km.core.service.reassign.impl.ReassignJobServiceImpl$$FastClassBySpringCGLIB$$56de3d89.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at com.xiaojukeji.know.streaming.km.core.service.reassign.impl.ReassignJobServiceImpl$$EnhancerBySpringCGLIB$$3857d1ac.verifyAndUpdateStatue(<generated>)
        at com.xiaojukeji.know.streaming.km.task.job.CommunityReassignJobTask.processClusterTask(CommunityReassignJobTask.java:36)
        at com.xiaojukeji.know.streaming.km.task.AbstractAsyncCommonDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncCommonDispatchTask.java:32)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.ElectionNotNeededException: Leader election not needed for topic partition
```

**Comment by WYAOBO** [comment]
我来认领该issue。
