### ISSUE TITLE
ZK健康巡检日志不清晰导致问题难定位

### ISSUE THREAD

**Issue by ZQKC** [didi/KnowStreaming#904]
如题，在健康巡检时，会出现空指针异常，出现的原因是ZK的四字命令获取指标失败导致指标为空，因此建议对日志进行优化。

日志信息：
```
2023-02-07 17:01:02.291 ERROR 11 --- [-2-9-thread-165] k.s.k.c.s.h.c.AbstractHealthCheckService : method=checkAndGetResult||clusterParam=ZookeeperParam(zkAddressList=[Tuple(v1=xxxxxx, v2=2181)], zkConfig=null)||clusterHealthConfig=HealthAmountRatioConfig(amount=100000, ratio=0.8)||errMsg=exception!

java.lang.NullPointerException: null
 at com.xiaojukeji.know.streaming.km.core.service.health.checker.zookeeper.HealthCheckZookeeperService.checkWatchCount(HealthCheckZookeeperService.java:178)
 at com.xiaojukeji.know.streaming.km.core.service.health.checker.AbstractHealthCheckService.checkAndGetResult(AbstractHealthCheckService.java:48)
 at com.xiaojukeji.know.streaming.km.task.kafka.health.AbstractHealthCheckTask.checkAndGetResult(AbstractHealthCheckTask.java:109)
 at com.xiaojukeji.know.streaming.km.task.kafka.health.AbstractHealthCheckTask.lambda$calAndUpdateHealthCheckResult$0(AbstractHealthCheckTask.java:60)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
```

代码位置：
com.xiaojukeji.know.streaming.km.core.service.health.checker.zookeeper.HealthCheckZookeeperService
![image](https://user-images.githubusercontent.com/4694454/217774528-fcbe14bf-153e-46c8-b473-8c7f5ac8b840.png)

**Comment by Luckywustone** [comment]
在健康巡检时，会出现空指针异常，出现的原因是ZK的四字命令获取指标失败导致指标为空，部分代码还未进行优化，因此建议对日志进行优化，
