### ISSUE TITLE
接入报错 No LoginModule found for org.apache.common.security.scram.ScramLoginModule

### ISSUE THREAD

**Issue by runkecheng** [didi/KnowStreaming#946]
- [X] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题

安装版本： KnowStreaming-3.0.0-beta.3

listener配置：

```
    ##########
    # Listener configuration: EXTERNAL-9094
    ##########
    listener.name.external-9094.scram-sha-512.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required;
    listener.name.external-9094.sasl.enabled.mechanisms=SCRAM-SHA-512


    ##########
    # Common listener configuration
    ##########
    listeners=CONTROLPLANE-9090://0.0.0.0:9090,REPLICATION-9091://0.0.0.0:9091,PLAIN-9092://0.0.0.0:9092,TLS-9093://0.0.0.0:9093,EXTERNAL-9094://0.0.0.0:9094
    advertised.listeners=CONTROLPLANE-9090://kafka-68521180-kafka-0.kafka-68521180-kafka-brokers.qfusion-admin.svc:9090,REPLICATION-9091://kafka-68521180-kafka-0.kafka-68521180-kafka-brokers.qfusion-admin.svc:9091,PLAIN-9092://kafka-68521180-kafka-0.kafka-68521180-kafka-brokers.qfusion-admin.svc:9092,TLS-9093://kafka-68521180-kafka-0.kafka-68521180-kafka-brokers.qfusion-admin.svc:9093,EXTERNAL-9094://${STRIMZI_NODEPORT_DEFAULT_ADDRESS}:30593
    listener.security.protocol.map=CONTROLPLANE-9090:SSL,REPLICATION-9091:SSL,PLAIN-9092:PLAINTEXT,TLS-9093:SSL,EXTERNAL-9094:SASL_PLAINTEXT
    control.plane.listener.name=CONTROLPLANE-9090
    inter.broker.listener.name=REPLICATION-9091
    sasl.enabled.mechanisms=
    ssl.secure.random.implementation=SHA1PRNG
    ssl.endpoint.identification.algorithm=HTTPS
```

```
2023-02-22 10:49:34.740 ERROR 7752 --- [nio-8080-exec-9] c.x.k.s.k.p.k.z.s.impl.KafkaZKDAOImpl    : method=checkBootstrapServersLegal||bootstrapServers=10.10.66.99:30593,10.10.66.99:30582,10.10.66.99:32083||clientProps={security.protocol=SASL_PLAINTEXT, key.deserializer=org.apache.kafka.common.serialization.StringDeserializer, value.deserializer=org.apache.kafka.common.serialization.StringDeserializer, sasl.mechanism=SCRAM-SHA-512, sasl.jaas.config=org.apache.common.security.scram.ScramLoginModule required username="root" password="E)La0YJWpRAoP2bTLZ1f*oOOwaMFUMaDj7ybc\XPC85WV5Qnbs7Sodyueyx08Vek";, bootstrap.servers=10.10.66.99:30593,10.10.66.99:30582,10.10.66.99:32083, ssl.secure.random.implementation=SHA1PRNG, sasl.enabled.mechanisms=true, ssl.endpoint.identification.algorithm=HTTPS}||errMsg=exception

org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:823)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:665)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:626)
        at com.xiaojukeji.know.streaming.km.core.service.cluster.impl.ClusterValidateServiceImpl.checkBSLegal(ClusterValidateServiceImpl.java:94)
        at com.xiaojukeji.know.streaming.km.core.service.cluster.impl.ClusterValidateServiceImpl.checkKafkaLegal(ClusterValidateServiceImpl.java:66)
        at com.xiaojukeji.know.streaming.km.rest.api.v3.util.UtilsController.validateKafka(UtilsController.java:43)
        at jdk.internal.reflect.GeneratedMethodAccessor435.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: No LoginModule found for org.apache.common.security.scram.ScramLoginModule
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:737)
        ... 59 common frames omitted
Caused by: javax.security.auth.login.LoginException: No LoginModule found for org.apache.common.security.scram.ScramLoginModule
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:710)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
        at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
        at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
        at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
        ... 63 common frames omitted
```

**Comment by ZQKC** [comment]
可以检查一下 sasl.jaas.config 这个配置，看着是 org.apache.common.security.scram.ScramLoginModule 这个写错了

**Comment by runkecheng** [comment]
> 可以检查一下 sasl.jaas.config 这个配置，看着是 org.apache.common.security.scram.ScramLoginModule 这个写错了


感谢回复，纠正拼写后又遇到了这个问题：https://github.com/didi/KnowStreaming/issues/878，但是没有在这个issue底下看到解决/排查方案

**Comment by ZQKC** [comment]
> > 可以检查一下 sasl.jaas.config 这个配置，看着是 org.apache.common.security.scram.ScramLoginModule 这个写错了
> 
> 感谢回复，纠正拼写后又遇到了这个问题：#878 但是没有在这个issue底下看到解决/排查方案

1、你接入集群时，填写的配置信息是？
2、这个集群搭建好之后，现在客户端已经可以正常使用了是吧？

**Comment by runkecheng** [comment]
> > > 可以检查一下 sasl.jaas.config 这个配置，看着是 org.apache.common.security.scram.ScramLoginModule 这个写错了
> > 
> > 
> > 感谢回复，纠正拼写后又遇到了这个问题：#878 但是没有在这个issue底下看到解决/排查方案
> 
> 1、你接入集群时，填写的配置信息是？ 2、这个集群搭建好之后，现在客户端已经可以正常使用了是吧？

找到问题了，是配置的用户权限不足。感谢回复
