### ISSUE TITLE
配置kerberos认证kafka集群

### ISSUE THREAD

**Issue by bigkjp97** [didi/KnowStreaming#976]
- [x] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

## 在这里提出你的问题

您好，请问按照FAQ的方式配置了Kerberos认证集群，出现以下报错，本地使用kinit -kt 可以认证成功

 INFO 98727 --- [a@KAFKA.COM] o.a.k.c.security.kerberos.KerberosLogin  : [Principal=kafka@KAFKA.COM]: TGT refresh thread started.2023-03-02 16:09:40.555  INFO 98727 --- [a@KAFKA.COM] o.a.k.c.security.kerberos.KerberosLogin  : [Principal=kafka@KAFKA.COM]: TGT valid starting at: Thu Mar 02 16:09:40 CST 2023
 INFO 98727 --- [a@KAFKA.COM] o.a.k.c.security.kerberos.KerberosLogin  : [Principal=kafka@KAFKA.COM]: TGT expires: Fri Mar 03 16:09:40 CST 2023
 INFO 98727 --- [a@KAFKA.COM] o.a.k.c.security.kerberos.KerberosLogin  : [Principal=kafka@KAFKA.COM]: TGT refresh sleeping until: Fri Mar 03 11:26:23 CST 2023

java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.ClusterAuthorizationException: Error listing groups on kafka1.kafka.com:9092 (id: 20 rack: null)
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
        at com.xiaojukeji.know.streaming.km.core.service.group.impl.GroupServiceImpl.listGroupsFromKafka(GroupServiceImpl.java:89)
        at com.xiaojukeji.know.streaming.km.collector.metric.kafka.GroupMetricCollector.collectKafkaMetrics(GroupMetricCollector.java:48)
        at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37)
        at com.xiaojukeji.know.streaming.km.task.kafka.metrics.GroupMetricCollectorTask.processClusterTask(GroupMetricCollectorTask.java:29)
        at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

WARN 98727 --- [a@KAFKA.COM] o.a.k.c.security.kerberos.KerberosLogin  : [Principal=kafka@KAFKA.COM]: TGT renewal thread has been interrupted and will exit.

**Comment by ZQKC** [comment]
> * [x]  我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。
> 
> ## 在这里提出你的问题
> 您好，请问按照FAQ的方式配置了Kerberos认证集群，出现以下报错，本地使用kinit -kt 可以认证成功
> 
> INFO 98727 --- [[a@KAFKA.COM](mailto:a@KAFKA.COM)] o.a.k.c.security.kerberos.KerberosLogin : [Principal=[kafka@KAFKA.COM](mailto:kafka@KAFKA.COM)]: TGT refresh thread started.2023-03-02 16:09:40.555 INFO 98727 --- [[a@KAFKA.COM](mailto:a@KAFKA.COM)] o.a.k.c.security.kerberos.KerberosLogin : [Principal=[kafka@KAFKA.COM](mailto:kafka@KAFKA.COM)]: TGT valid starting at: Thu Mar 02 16:09:40 CST 2023 INFO 98727 --- [[a@KAFKA.COM](mailto:a@KAFKA.COM)] o.a.k.c.security.kerberos.KerberosLogin : [Principal=[kafka@KAFKA.COM](mailto:kafka@KAFKA.COM)]: TGT expires: Fri Mar 03 16:09:40 CST 2023 INFO 98727 --- [[a@KAFKA.COM](mailto:a@KAFKA.COM)] o.a.k.c.security.kerberos.KerberosLogin : [Principal=[kafka@KAFKA.COM](mailto:kafka@KAFKA.COM)]: TGT refresh sleeping until: Fri Mar 03 11:26:23 CST 2023
> 
> java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.ClusterAuthorizationException: Error listing groups on kafka1.kafka.com:9092 (id: 20 rack: null) at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) at com.xiaojukeji.know.streaming.km.core.service.group.impl.GroupServiceImpl.listGroupsFromKafka(GroupServiceImpl.java:89) at com.xiaojukeji.know.streaming.km.collector.metric.kafka.GroupMetricCollector.collectKafkaMetrics(GroupMetricCollector.java:48) at com.xiaojukeji.know.streaming.km.collector.metric.kafka.AbstractKafkaMetricCollector.collectMetrics(AbstractKafkaMetricCollector.java:37) at com.xiaojukeji.know.streaming.km.task.kafka.metrics.GroupMetricCollectorTask.processClusterTask(GroupMetricCollectorTask.java:29) at com.xiaojukeji.know.streaming.km.task.kafka.metrics.AbstractAsyncMetricsDispatchTask.lambda$asyncProcessSubTask$0(AbstractAsyncMetricsDispatchTask.java:33) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)
> 
> WARN 98727 --- [[a@KAFKA.COM](mailto:a@KAFKA.COM)] o.a.k.c.security.kerberos.KerberosLogin : [Principal=[kafka@KAFKA.COM](mailto:kafka@KAFKA.COM)]: TGT renewal thread has been interrupted and will exit.

接入集群的配置是？权限这些是否正常？我看是进行listGroup的时候，报认证失败

**Comment by bigkjp97** [comment]
```json
{
  "security.protocol": "SASL_PLAINTEXT",
  "sasl.mechanism": "GSSAPI",
  "sasl.jaas.config": "com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true keyTab=\"/etc/keytab/kafka.keytab\" storeKey=true useTicketCache=false principal=\"kafka@KAFKA.COM\";",
  "sasl.kerberos.service.name": "kafka"
}
```
用的是这样的配置

**Comment by ZQKC** [comment]
> 权限这些是否正常？我看是进行listGroup的时候，报认证失败

权限这些是否正常？我看是进行listGroup的时候，报认证失败

**Comment by ZQKC** [comment]
无更多反馈，关闭该问题
