### ISSUE TITLE
集群删除后，后台报NullPointerException

### ISSUE THREAD

**Issue by luoze-god** [didi/KnowStreaming#979]
2023-03-03 15:21:09.846 [MetricCollect-Shard-2-9-thread-14] ERROR class=c.x.k.s.k.c.m.c.ConnectConnectorMetricCollector||method=collectMetrics||connectClusterId=1||connectorName=SqlserverGongyinglianLGBS12||metric=CollectMetrics
CostTimeUnitSec||errMsg=exception!
java.lang.NullPointerException: null
        at com.xiaojukeji.know.streaming.km.core.service.connect.connector.impl.ConnectorMetricServiceImpl.getConnectorMetric(ConnectorMetricServiceImpl.java:250)
        at com.xiaojukeji.know.streaming.km.core.service.connect.connector.impl.ConnectorMetricServiceImpl.getConnectWorkerMetricSum(ConnectorMetricServiceImpl.java:231)
        at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)
        at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)
        at com.xiaojukeji.know.streaming.km.core.service.version.BaseConnectorVersionControlService.doVCHandler(BaseConnectorVersionControlService.java:31)
        at com.xiaojukeji.know.streaming.km.core.service.connect.connector.impl.ConnectorMetricServiceImpl.collectConnectClusterMetricsFromKafka(ConnectorMetricServiceImpl.java:144)
        at com.xiaojukeji.know.streaming.km.collector.metric.connect.ConnectConnectorMetricCollector.collectMetrics(ConnectConnectorMetricCollector.java:85)
        at com.xiaojukeji.know.streaming.km.collector.metric.connect.ConnectConnectorMetricCollector.lambda$collectConnectMetrics$0(ConnectConnectorMetricCollector.java:60)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2023-03-03 15:21:09.814 [MetricCollect-Shard-0-7-thread-45] ERROR class=c.x.k.s.km.persistence.connect.ConnectJMXClient||method=getClientWithCheck||connectClusterId=1||workerId=10.91.xxx.xxx:8083||msg=get jmx connector failed!
2023-03-03 15:21:09.925 [MetricCollect-Shard-0-7-thread-45] ERROR class=c.x.k.s.k.c.s.h.c.c.HealthCheckConnectorService||method=getHealthCompareResult||connectClusterId=1||connectorName=tempqlinkapqpspare||metricName=ConnectorUn
assignedTaskCount||errMsg=get metrics failed

**Comment by luoze-god** [comment]
可以直接删除know_streaming库，然后重新初始化
