### ISSUE TITLE
3.3.0获取zk监控指标异常

### ISSUE THREAD

**Issue by whq-cjh** [didi/KnowStreaming#983]
- [ ] 我已经在 [issues](https://github.com/didi/KnowStreaming/issues) 搜索过相关问题了,并没有重复的。

 你是否希望来认领这个Bug。

 「   Y   /   N  」

### 环境信息

* KnowStreaming version :   <font size=4 color =red>   3.3.0 </font>
* Operating System version :  <font size=4 color =red> helm部署 </font>
* Java version : <font size=4 color =red> 1.8 </font>

### 重现该问题的步骤

![image](https://user-images.githubusercontent.com/29394397/226268896-97a587e7-a221-45e1-9097-9d3a8580fb8b.png)
![image](https://user-images.githubusercontent.com/29394397/226269138-c42cc247-ff5a-4d02-91d1-2981701eab3b.png)

### 实际结果

---

如果有异常，请附上异常Trace:
java.lang.NumberFormatException: For input string: "5.0"

2023-03-20T14:47:04.160830690+08:00 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)

2023-03-20T14:47:04.160833959+08:00 	at java.lang.Long.parseLong(Long.java:589)

2023-03-20T14:47:04.160836647+08:00 	at java.lang.Long.valueOf(Long.java:803)

2023-03-20T14:47:04.160839450+08:00 	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.lambda$parseAndInitData$0(MonitorCmdDataParser.java:76)

2023-03-20T14:47:04.160842312+08:00 	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)

2023-03-20T14:47:04.160845893+08:00 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)

2023-03-20T14:47:04.160848082+08:00 	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:54)

2023-03-20T14:47:04.160849873+08:00 	at com.xiaojukeji.know.streaming.km.common.bean.entity.zookeeper.fourletterword.parser.MonitorCmdDataParser.parseAndInitData(MonitorCmdDataParser.java:30)

2023-03-20T14:47:04.160851861+08:00 	at com.xiaojukeji.know.streaming.km.common.utils.zookeeper.FourLetterWordUtil.executeFourLetterCmd(FourLetterWordUtil.java:56)

2023-03-20T14:47:04.160853836+08:00 	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.getMetricFromMonitorCmd(ZookeeperMetricServiceImpl.java:234)

2023-03-20T14:47:04.160855887+08:00 	at com.xiaojukeji.know.streaming.km.core.service.version.impl.VersionControlServiceImpl.doHandler(VersionControlServiceImpl.java:93)

2023-03-20T14:47:04.160857593+08:00 	at com.xiaojukeji.know.streaming.km.core.service.version.BaseVersionControlService.doVCHandler(BaseVersionControlService.java:62)

2023-03-20T14:47:04.160864262+08:00 	at com.xiaojukeji.know.streaming.km.core.service.version.BaseKafkaVersionControlService.doVCHandler(BaseKafkaVersionControlService.java:29)

2023-03-20T14:47:04.160866901+08:00 	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.collectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:97)

2023-03-20T14:47:04.160869527+08:00 	at com.xiaojukeji.know.streaming.km.core.service.zookeeper.impl.ZookeeperMetricServiceImpl.batchCollectMetricsFromZookeeper(ZookeeperMetricServiceImpl.java:135)

2023-03-20T14:47:04.160872079+08:00 	at com.xiaojukeji.know.streaming.km.biz.cluster.impl.ClusterZookeepersManagerImpl.getClusterPhyZookeepersState(ClusterZookeepersManagerImpl.java:85)

2023-03-20T14:47:04.160874737+08:00 	at com.xiaojukeji.know.streaming.km.rest.api.v3.cluster.ClusterZookeepersController.getClusterZookeepersState(ClusterZookeepersController.java:38)

2023-03-20T14:47:04.160877287+08:00 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2023-03-20T14:47:04.160879999+08:00 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

2023-03-20T14:47:04.160882803+08:00 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2023-03-20T14:47:04.160885500+08:00 	at java.lang.reflect.Method.invoke(Method.java:498)

2023-03-20T14:47:04.160888894+08:00 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)

2023-03-20T14:47:04.160891901+08:00 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)

2023-03-20T14:47:04.160894655+08:00 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)

2023-03-20T14:47:04.160897898+08:00 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)

2023-03-20T14:47:04.160900437+08:00 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)

2023-03-20T14:47:04.160903188+08:00 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

2023-03-20T14:47:04.160905953+08:00 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)

2023-03-20T14:47:04.160908371+08:00 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)

2023-03-20T14:47:04.160911277+08:00 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

2023-03-20T14:47:04.160913945+08:00 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)

2023-03-20T14:47:04.160916157+08:00 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)

2023-03-20T14:47:04.160918465+08:00 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

2023-03-20T14:47:04.160921485+08:00 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)

2023-03-20T14:47:04.160938653+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

2023-03-20T14:47:04.160941589+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2023-03-20T14:47:04.160944505+08:00 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

2023-03-20T14:47:04.160946904+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2023-03-20T14:47:04.160951975+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2023-03-20T14:47:04.160954506+08:00 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

2023-03-20T14:47:04.160957307+08:00 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

2023-03-20T14:47:04.160959843+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2023-03-20T14:47:04.160962169+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2023-03-20T14:47:04.160964840+08:00 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)

2023-03-20T14:47:04.160967779+08:00 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

2023-03-20T14:47:04.160970991+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2023-03-20T14:47:04.160973519+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2023-03-20T14:47:04.160984521+08:00 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)

2023-03-20T14:47:04.160991105+08:00 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

2023-03-20T14:47:04.160993912+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2023-03-20T14:47:04.160996405+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2023-03-20T14:47:04.160998937+08:00 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)

2023-03-20T14:47:04.161001718+08:00 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

2023-03-20T14:47:04.161004378+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2023-03-20T14:47:04.161006829+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2023-03-20T14:47:04.161009566+08:00 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

2023-03-20T14:47:04.161012379+08:00 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)

2023-03-20T14:47:04.161015506+08:00 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)

2023-03-20T14:47:04.161017888+08:00 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)

2023-03-20T14:47:04.161020631+08:00 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

2023-03-20T14:47:04.161023154+08:00 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)

2023-03-20T14:47:04.161025605+08:00 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)

2023-03-20T14:47:04.161027957+08:00 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

2023-03-20T14:47:04.161030709+08:00 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)

2023-03-20T14:47:04.161033117+08:00 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)

2023-03-20T14:47:04.161035544+08:00 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)

2023-03-20T14:47:04.161038253+08:00 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)

2023-03-20T14:47:04.161042320+08:00 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

2023-03-20T14:47:04.161052944+08:00 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

2023-03-20T14:47:04.161055820+08:00 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

2023-03-20T14:47:04.161058371+08:00 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

2023-03-20T14:47:04.161061294+08:00 	at java.lang.Thread.run(Thread.java:745)
```
Just put your stack trace here!
```

**Comment by ZQKC** [comment]
已修复：https://github.com/didi/KnowStreaming/commit/c71865f6238d146c80e389a962d8c1dd9833419c
